FROM node:18 as build

WORKDIR /app

COPY package.json .

RUN npm install -g npm@latest

RUN npm install

COPY . .

EXPOSE 4000

CMD [ "npm","run","build" ]


FROM nginx

COPY  --from=build /app/build /usr/share/nginx/html 

EXPOSE 80










